# deployment/backend.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Start with 1 replica to keep it simple
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # This is the full, correct name of your image on Docker Hub
        image: joyobichie/gene-predictor-app-backend:latest
        imagePullPolicy: Always # Tells K8s to always check for a new version
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "a-very-secure-key-for-development"
        - name: DEBUG
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    # This connects the Service to the Pods with the 'app: backend' label
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000