# deployment/frontend.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1 # Start with 1 replica
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # This is the full, correct name of your image on Docker Hub
        image: joyobichie/gene-predictor-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
          # This URL must point to the backend Service name, not localhost
        - name: VITE_API_URL
          value: "http://backend-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # This makes the service accessible from your browser via localhost
  type: LoadBalancer
  selector:
    # This connects the Service to the Pods with the 'app: frontend' label
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173